# services/tts.py

import os
import base64
import asyncio
import hashlib
import logging
from typing import Optional

from agent.language import (
    make_speech_friendly,
    get_azure_voice,
    AZURE_VOICE_MAP
)

logger = logging.getLogger(__name__)

# Simple in-memory TTS cache
# Key: MD5(text + language), Value: base64 audio
_cache: dict[str, str] = {}
_CACHE_MAX = 300


class TTSService:

    def __init__(self):
        self.provider        = os.getenv('TTS_PROVIDER', 'browser').lower()
        self.azure_key       = os.getenv('AZURE_SPEECH_KEY', '')
        self.azure_region    = os.getenv('AZURE_SPEECH_REGION', 'eastus')
        self.elevenlabs_key  = os.getenv('ELEVENLABS_API_KEY', '')
        self.groq_api_key    = os.getenv('GROQ_API_KEY', '')
        self.google_api_key  = os.getenv('GOOGLE_TTS_API_KEY', '')
        logger.info(f"TTS provider: {self.provider}")

    def audio_format(self) -> str:
        """Returns the audio format this provider outputs."""
        if self.provider in ('elevenlabs', 'google', 'azure'):
            return 'mp3'
        return 'wav'  # groq/openai orpheus outputs WAV

    async def synthesize(
        self,
        text: str,
        language: str = 'en',
        skip_cache: bool = False
    ) -> Optional[str]:
        """
        Convert text to base64 MP3 audio.
        Returns None if provider is 'browser' (frontend handles it).
        
        IMPORTANT: make_speech_friendly() is called HERE automatically.
        Do NOT call it before passing text to this function.
        """
        if not text or not text.strip():
            return None

        # Strip model reasoning/thinking blocks before speech synthesis
        import re
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
        text = re.sub(r"<reasoning>.*?</reasoning>", "", text, flags=re.DOTALL).strip()
        if not text:
            return None

        # Make speech-friendly FIRST
        speech_text = make_speech_friendly(text, language)
        if not speech_text:
            return None

        # Cache key includes provider so that changing TTS provider doesn't
        # serve stale audio generated by the previous provider.
        cache_key = hashlib.md5(
            f"{self.provider}:{speech_text}:{language}".encode()
        ).hexdigest()

        if not skip_cache and cache_key in _cache:
            logger.debug(f"TTS cache hit for lang={language}")
            return _cache[cache_key]

        # Route to provider
        audio_b64 = None
        try:
            if self.provider == 'azure' and self.azure_key:
                audio_b64 = await self._azure(speech_text, language)

            elif self.provider == 'google' and self.google_api_key:
                audio_b64 = await self._google(speech_text, language)

            elif self.provider == 'elevenlabs' and self.elevenlabs_key:
                audio_b64 = await self._elevenlabs(speech_text, language)

            elif self.provider == 'groq' and self.groq_api_key:
                audio_b64 = await self._groq(speech_text)

            else:
                # Browser TTS — return None, frontend handles it
                return None

        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "rate_limit" in err_str.lower():
                logger.warning("TTS rate-limited (%s) — falling back to browser TTS", self.provider)
            else:
                logger.error("TTS failed (%s): %s", self.provider, e)
            return None

        # Cache the result
        if audio_b64:
            if len(_cache) >= _CACHE_MAX:
                # Remove oldest entry
                del _cache[next(iter(_cache))]
            _cache[cache_key] = audio_b64

        return audio_b64

    # ── Azure Neural TTS ───────────────────────────────────────────────────
    async def _azure(self, text: str, language: str) -> Optional[str]:
        """
        Azure Neural TTS — RECOMMENDED for Indian languages.
        Free tier: 500,000 characters/month.
        Supports: hi-IN, ml-IN, ta-IN, te-IN, bn-IN, en-IN
        """
        try:
            import azure.cognitiveservices.speech as sdk
        except ImportError:
            logger.error(
                "azure-cognitiveservices-speech not installed. "
                "Run: pip install azure-cognitiveservices-speech"
            )
            return None

        voice  = get_azure_voice(language)
        ssml   = self._build_ssml(text, voice, language)
        config = sdk.SpeechConfig(
            subscription=self.azure_key,
            region=self.azure_region
        )
        config.set_speech_synthesis_output_format(
            sdk.SpeechSynthesisOutputFormat.Audio16Khz32KBitRateMonoMp3
        )

        loop = asyncio.get_event_loop()

        def _synth():
            synth  = sdk.SpeechSynthesizer(
                speech_config=config,
                audio_config=None
            )
            result = synth.speak_ssml_async(ssml).get()

            if result.reason == sdk.ResultReason.SynthesizingAudioCompleted:
                return result.audio_data
            else:
                cd = result.cancellation_details
                raise RuntimeError(
                    f"Azure TTS error: {cd.reason} — {cd.error_details}"
                )

        audio_data = await loop.run_in_executor(None, _synth)
        return base64.b64encode(audio_data).decode('utf-8')

    def _build_ssml(
        self, text: str, voice: str, language: str
    ) -> str:
        """Build SSML with natural prosody for Indian voices."""
        # Escape XML special characters
        safe = (text
            .replace('&',  '&amp;')
            .replace('<',  '&lt;')
            .replace('>',  '&gt;')
            .replace('"',  '&quot;')
            .replace("'",  '&apos;')
        )

        # Add natural pauses
        import re
        safe = re.sub(r'([.!?])\s+', r'\1<break time="280ms"/> ', safe)
        safe = re.sub(r'([,;])\s+',  r'\1<break time="120ms"/> ', safe)

        lang_codes = {
            'en': 'en-IN', 'hi': 'hi-IN', 'ml': 'ml-IN',
            'ta': 'ta-IN', 'te': 'te-IN', 'bn': 'bn-IN',
            'kn': 'kn-IN', 'gu': 'gu-IN', 'pa': 'pa-IN',
        }
        xml_lang = lang_codes.get(language, 'en-IN')

        return (
            f'<speak version="1.0" '
            f'xmlns="http://www.w3.org/2001/10/synthesis" '
            f'xmlns:mstts="http://www.w3.org/2001/mstts" '
            f'xml:lang="{xml_lang}">'
            f'<voice name="{voice}">'
            f'<mstts:express-as style="customerservice" styledegree="0.8">'
            f'<prosody rate="0.97" pitch="+2Hz">'
            f'{safe}'
            f'</prosody>'
            f'</mstts:express-as>'
            f'</voice>'
            f'</speak>'
        )

    # ── Google Cloud TTS ───────────────────────────────────────────────────
    # Free tier: 1,000,000 WaveNet chars/month — sweet, natural Indian voices
    # Setup: Google Cloud Console → enable "Cloud Text-to-Speech API" → API Keys
    # .env: TTS_PROVIDER=google  GOOGLE_TTS_API_KEY=AIza...
    #
    # Best voices per language:
    #   en → en-IN-Wavenet-A (female, warm Indian English) ← default
    #   hi → hi-IN-Wavenet-A (female Hindi)
    #   ml → ml-IN-Wavenet-A (female Malayalam)
    #   ta → ta-IN-Wavenet-A (female Tamil)
    #   te → te-IN-Wavenet-A (female Telugu)
    #   bn → bn-IN-Wavenet-A (female Bengali)
    #   kn → kn-IN-Wavenet-A (female Kannada)

    # Neural2 voices: most natural Google TTS, trained on real speech data
    # Journey voices (en only): most conversational, designed for dialogue
    _GOOGLE_VOICES = {
        'en': ('en-IN', 'en-IN-Journey-F'),   # Journey: most natural, conversational
        'hi': ('hi-IN', 'hi-IN-Neural2-A'),   # Neural2: best quality for Hindi
        'ml': ('ml-IN', 'ml-IN-Wavenet-A'),
        'ta': ('ta-IN', 'ta-IN-Neural2-A'),
        'te': ('te-IN', 'te-IN-Neural2-A'),
        'bn': ('bn-IN', 'bn-IN-Wavenet-A'),
        'kn': ('kn-IN', 'kn-IN-Wavenet-A'),
        'gu': ('gu-IN', 'gu-IN-Wavenet-A'),
        'pa': ('pa-IN', 'pa-IN-Wavenet-B'),
    }

    async def _google(self, text: str, language: str) -> Optional[str]:
        import httpx
        lang_code, voice_name = self._GOOGLE_VOICES.get(language, ('en-IN', 'en-IN-Journey-F'))
        payload = {
            "input": {"text": text},
            "voice": {
                "languageCode": lang_code,
                "name": voice_name,
                "ssmlGender": "FEMALE"
            },
            "audioConfig": {
                "audioEncoding": "MP3",
                "speakingRate": 0.9,
                "pitch": 0.0,
                "effectsProfileId": ["small-bluetooth-speaker-class-device"]
            }
        }
        async with httpx.AsyncClient(timeout=12.0) as client:
            r = await client.post(
                "https://texttospeech.googleapis.com/v1/text:synthesize",
                params={"key": self.google_api_key},
                json=payload,
            )
            r.raise_for_status()
            data = r.json()
            return data.get("audioContent")  # already base64 MP3

    # ── ElevenLabs TTS ─────────────────────────────────────────────────────
    # Rachel: warm, natural, conversational — the most human-sounding free-tier voice.
    # Dramatically less robotic than Bella for voice-first shopping assistants.
    # Jessica: warm, conversational, very human-sounding (recommended)
    # Fallback: Rachel (21m00Tcm4TlvDq8ikWAM) — free tier, always available
    _EL_VOICE_ID = "cgSgspJ2msm6clMCkdW9"  # Jessica

    # Max chars to send to ElevenLabs — long text causes timeouts and poor decoding
    _EL_MAX_CHARS = 500

    async def _elevenlabs(
        self, text: str, language: str
    ) -> Optional[str]:
        import httpx

        # Truncate at sentence boundary to avoid mid-word cuts
        if len(text) > self._EL_MAX_CHARS:
            cut = text.rfind('. ', 0, self._EL_MAX_CHARS)
            text = (text[:cut + 1] if cut > 60 else text[:self._EL_MAX_CHARS]) + '.'

        async with httpx.AsyncClient(timeout=25.0) as client:
            r = await client.post(
                f"https://api.elevenlabs.io/v1/text-to-speech/{self._EL_VOICE_ID}",
                headers={
                    "Accept":       "audio/mpeg",
                    "xi-api-key":   self.elevenlabs_key,
                    "Content-Type": "application/json"
                },
                params={"output_format": "mp3_44100_128"},
                json={
                    "text": text,
                    # eleven_turbo_v2_5 — best quality/latency balance for live calls.
                    # Significantly more natural than flash; ~1.5s vs ~0.8s latency.
                    "model_id": "eleven_turbo_v2_5",
                    "voice_settings": {
                        "stability": 0.35,          # lower = more natural pitch variation (less robotic)
                        "similarity_boost": 0.75,   # voice character retention
                        "style": 0.30,              # expressiveness — warmth and conversational tone
                        "use_speaker_boost": True
                    }
                }
            )
            if r.status_code == 404 and self._EL_VOICE_ID != "21m00Tcm4TlvDq8ikWAM":
                # Voice not available on this account — retry with Rachel (free tier)
                logger.warning("ElevenLabs voice %s not found, retrying with Rachel", self._EL_VOICE_ID)
                r = await client.post(
                    "https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM",
                    headers={"Accept": "audio/mpeg", "xi-api-key": self.elevenlabs_key, "Content-Type": "application/json"},
                    params={"output_format": "mp3_44100_128"},
                    json={"text": text, "model_id": "eleven_turbo_v2_5",
                          "voice_settings": {"stability": 0.35, "similarity_boost": 0.75, "style": 0.30, "use_speaker_boost": True}},
                )
            if r.status_code != 200:
                logger.error(
                    "ElevenLabs HTTP %s: %s",
                    r.status_code, r.text[:300]
                )
                return None
            # Validate we got real MP3 data (not an error JSON)
            ct = r.headers.get("content-type", "")
            if "application/json" in ct or "text/" in ct:
                logger.error("ElevenLabs returned non-audio content-type %r: %s", ct, r.text[:200])
                return None
            if len(r.content) < 512:
                logger.error("ElevenLabs returned suspiciously small audio (%d bytes)", len(r.content))
                return None
            return base64.b64encode(r.content).decode('utf-8')

    # ── Groq TTS (free, English only) ─────────────────────────────────────
    async def _groq(self, text: str) -> Optional[str]:
        from groq import AsyncGroq
        client = AsyncGroq(api_key=self.groq_api_key)
        response = await client.audio.speech.create(
            model="canopylabs/orpheus-v1-english",
            voice="diana",  # available female voices: autumn, diana, hannah
            input=text,
            response_format="wav"
        )
        audio_bytes = await response.read()
        return base64.b64encode(audio_bytes).decode('utf-8')


# ── Singleton ──────────────────────────────────────────────────────────────
_tts_instance: Optional[TTSService] = None

def get_tts_service() -> TTSService:
    global _tts_instance
    if _tts_instance is None:
        _tts_instance = TTSService()
    return _tts_instance
